from __future__ import annotations

from .base import LeaderPlanRequest


class FakeLeaderProvider:
    name = "fake"

    def plan(self, request: LeaderPlanRequest) -> dict[str, object]:
        steps = []
        for index, agent in enumerate(request.config.agents, start=1):
            steps.append(
                {
                    "step": index,
                    "agent_id": agent.agent_id,
                    "role": agent.role,
                    "task": self._task_for_role(request.task, agent.role),
                    "risk": "requires human review before dispatch",
                    "requires_approval": True,
                }
            )
        return {
            "goal": request.task,
            "summary": "Plan generated by fake provider for local dry-run.",
            "steps": steps,
            "approval_required": True,
            "dispatch_ready": False,
        }

    def _task_for_role(self, task: str, role: str) -> str:
        normalized = role.lower()
        if "plan" in normalized:
            return f"Break down the goal and identify risks: {task}"
        if "implement" in normalized or "code" in normalized:
            return f"Implement the approved slice after planning: {task}"
        if "review" in normalized:
            return f"Review the implementation plan and verification evidence: {task}"
        return f"Contribute to the goal according to this role: {task}"
